package org.pramana.sdk;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Cross-language consistency tests.
 * These UUIDs were generated by the Python SDK and must match exactly.
 */
class CrossLanguageTest {

    @Test
    void testGintPramanaIdMatchesPython() {
        // Python: Gint(3, 4).pramana_id == "af506874-c410-5de4-8724-f90ad762c011"
        Gint z = new Gint(3, 4);
        assertEquals("af506874-c410-5de4-8724-f90ad762c011", z.pramanaId().toString());
    }

    @Test
    void testGaussOnePramanaIdMatchesPython() {
        // Python: Gauss(1, 0).pramana_id == "eda5f179-49f8-5be3-97ba-8e0ea5cb2769"
        Gauss one = new Gauss(1);
        assertEquals("eda5f179-49f8-5be3-97ba-8e0ea5cb2769", one.pramanaId().toString());
    }

    @Test
    void testGintAndGaussProduceSameId() {
        // A Gint and its Gauss equivalent must produce the same Pramana ID
        Gint z = new Gint(5, -3);
        Gauss g = z.toGauss();
        assertEquals(z.pramanaId(), g.pramanaId());
    }
}
